from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent

CLIENT_SECRET_FILE = PROJECT_ROOT / "client_secret.json"
TOKEN_FILE = PROJECT_ROOT / "token.json"
UPLOADS_DIR = PROJECT_ROOT / "uploads"
UPLOADED_DIR = PROJECT_ROOT / "uploaded"
STORIES_DIR = PROJECT_ROOT / "stories"
APPROVED_STORIES_DIR = STORIES_DIR / "approved"
USED_STORIES_DIR = STORIES_DIR / "used"
AUDIO_DIR = PROJECT_ROOT / "audio"
VIDEOS_DIR = PROJECT_ROOT / "videos"
DOWNLOADS_DIR = PROJECT_ROOT / "downloads"
OUTPUT_DIR = PROJECT_ROOT / "output"
LOGS_DIR = PROJECT_ROOT / "logs"
PUBLIC_DIR = PROJECT_ROOT / "public"
LOGO_FILE = PUBLIC_DIR / "logo.png"

PEXELS_API_KEY_ENV = "PEXELS_API_KEY"
GEMINI_API_KEY_ENV = "GEMINI_API_KEY"
GEMINI_TTS_MODEL = "gemini-2.5-flash-preview-tts"
GEMINI_TTS_VOICE = "Iapetus"
INSTAGRAM_ACCESS_TOKEN_ENV = "INSTAGRAM_ACCESS_TOKEN"
INSTAGRAM_USER_ID_ENV = "INSTAGRAM_USER_ID"
INSTAGRAM_PUBLIC_VIDEO_BASE_URL_ENV = "INSTAGRAM_PUBLIC_VIDEO_BASE_URL"
INSTAGRAM_GRAPH_API_VERSION_ENV = "INSTAGRAM_GRAPH_API_VERSION"
INSTAGRAM_GRAPH_BASE_URL_ENV = "INSTAGRAM_GRAPH_BASE_URL"
DEFAULT_INSTAGRAM_GRAPH_API_VERSION = "v25.0"
DEFAULT_INSTAGRAM_GRAPH_BASE_URL = "https://graph.instagram.com"
CLOUDINARY_CLOUD_NAME_ENV = "CLOUDINARY_CLOUD_NAME"
CLOUDINARY_API_KEY_ENV = "CLOUDINARY_API_KEY"
CLOUDINARY_API_SECRET_ENV = "CLOUDINARY_API_SECRET"
CLOUDINARY_FOLDER_ENV = "CLOUDINARY_FOLDER"
DEFAULT_CLOUDINARY_FOLDER = "the-ashy-notes/reels"

DEFAULT_PRIVACY_STATUS = "private"
DEFAULT_CATEGORY_ID = "22"  # People & Blogs

YOUTUBE_SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]
SUPPORTED_VIDEO_EXTENSIONS = {".mp4", ".mov", ".m4v", ".avi", ".mkv"}
SUPPORTED_AUDIO_EXTENSIONS = {".mp3", ".wav", ".m4a", ".aac", ".flac", ".ogg"}

VIDEO_WIDTH = 1080
VIDEO_HEIGHT = 1920
MIN_SHORT_DURATION_SECONDS = 30
MAX_SHORT_DURATION_SECONDS = 60
